# Generated by Django 5.1.14 on 2025-11-26 05:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("employee_id", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_photo", models.ImageField(upload_to="profile_photos/")),
                (
                    "mobile_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PulleyDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_image", models.ImageField(upload_to="uploads/")),
                ("result_image", models.ImageField(upload_to="results/")),
                ("temperature_c", models.FloatField(blank=True, null=True)),
                ("htl_value", models.FloatField(blank=True, null=True)),
                ("dist_p1_p2", models.FloatField(blank=True, null=True)),
                ("dist_p2_p3", models.FloatField(blank=True, null=True)),
                ("total_distance", models.FloatField(blank=True, null=True)),
                ("expected_total", models.FloatField(blank=True, null=True)),
                ("loss_mm", models.FloatField(blank=True, null=True)),
                ("distances", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetectionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "dist12",
                    models.FloatField(
                        blank=True,
                        help_text="Distance between pulley 1 and 2 (mm)",
                        null=True,
                    ),
                ),
                (
                    "dist23",
                    models.FloatField(
                        blank=True,
                        help_text="Distance between pulley 2 and 3 (mm)",
                        null=True,
                    ),
                ),
                (
                    "total",
                    models.FloatField(
                        blank=True, help_text="Total distance P1->P3 (mm)", null=True
                    ),
                ),
                (
                    "expected_total",
                    models.FloatField(
                        blank=True, help_text="Expected total distance (mm)", null=True
                    ),
                ),
                (
                    "expected_dist12",
                    models.FloatField(
                        blank=True, help_text="Expected distance P1->P2 (mm)", null=True
                    ),
                ),
                (
                    "expected_dist23",
                    models.FloatField(
                        blank=True, help_text="Expected distance P2->P3 (mm)", null=True
                    ),
                ),
                (
                    "loss_mm",
                    models.FloatField(
                        blank=True, help_text="Loss vs expected (mm)", null=True
                    ),
                ),
                (
                    "pulley_count",
                    models.IntegerField(
                        default=0, help_text="Number of pulleys detected"
                    ),
                ),
                (
                    "temperature_c",
                    models.FloatField(
                        blank=True, help_text="Temperature in Celsius", null=True
                    ),
                ),
                (
                    "points_json",
                    models.TextField(
                        blank=True, help_text="Pulley center points", null=True
                    ),
                ),
                (
                    "image_path",
                    models.ImageField(
                        blank=True,
                        help_text="Saved annotated image file",
                        null=True,
                        upload_to="best_captures/",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="pulley_app__timesta_7605a6_idx"
                    )
                ],
            },
        ),
    ]
